# setup_env.ps1 - Auto-generate .env file with secure values (PowerShell)

if (Test-Path .env) {
    Write-Host "⚠️  .env already exists. Delete it first if you want to regenerate." -ForegroundColor Yellow
    exit 1
}

Write-Host "🔧 Generating .env file with secure random values..." -ForegroundColor Cyan

# Generate secure random values
function Get-RandomHex {
    param([int]$Length)
    $bytes = New-Object byte[] ($Length / 2)
    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::Create()
    $rng.GetBytes($bytes)
    return ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
}

$POSTGRES_PASSWORD = Get-RandomHex -Length 32
$JWT_SECRET = Get-RandomHex -Length 64
$VERIDION_MASTER_KEY = Get-RandomHex -Length 64

# Create .env file
$envContent = @"
# Auto-generated by setup_env.ps1
# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

# Database
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_USER=veridion
POSTGRES_DB=veridion_nexus
DATABASE_URL=postgresql://veridion:$POSTGRES_PASSWORD@postgres:5432/veridion_nexus

# Security
JWT_SECRET=$JWT_SECRET
VERIDION_MASTER_KEY=$VERIDION_MASTER_KEY

# API Configuration
RUST_LOG=info
SERVER_HOST=0.0.0.0
SERVER_PORT=8080

# eIDAS (Optional - mock mode)
USE_REAL_API=false

# Notifications (Optional - disabled by default)
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
"@

$envContent | Out-File -FilePath .env -Encoding utf8 -NoNewline

Write-Host "✅ .env file created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "To start Veridion Nexus:"
Write-Host "  docker-compose up --build"
Write-Host ""
Write-Host "To run tests:"
Write-Host "  .\test_system.ps1"

