#!/bin/bash

# setup_env.sh - Auto-generate .env file with secure values

if [ -f .env ]; then
    echo "⚠️  .env already exists. Delete it first if you want to regenerate."
    exit 1
fi

echo "🔧 Generating .env file with secure random values..."

# Generate secure random values
POSTGRES_PASSWORD=$(openssl rand -hex 16)
JWT_SECRET=$(openssl rand -hex 32)
VERIDION_MASTER_KEY=$(openssl rand -hex 32)

# Create .env file
cat > .env << EOF
# Auto-generated by setup_env.sh
# Generated: $(date)

# Database
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_USER=veridion
POSTGRES_DB=veridion_nexus
DATABASE_URL=postgresql://veridion:$POSTGRES_PASSWORD@postgres:5432/veridion_nexus

# Security
JWT_SECRET=$JWT_SECRET
VERIDION_MASTER_KEY=$VERIDION_MASTER_KEY

# API Configuration
RUST_LOG=info
SERVER_HOST=0.0.0.0
SERVER_PORT=8080

# eIDAS (Optional - mock mode)
USE_REAL_API=false

# Notifications (Optional - disabled by default)
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
EOF

echo "✅ .env file created successfully!"
echo ""
echo "To start Veridion Nexus:"
echo "  docker-compose up --build"
echo ""
echo "To run tests:"
echo "  ./test_system.sh"

